#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/cloudydesk/cloudydesk /usr/bin/cloudydesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/cloudydesk.service ]; then
			rm /etc/systemd/system/cloudydesk.service /usr/lib/systemd/system/cloudydesk.service /usr/lib/systemd/user/cloudydesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/cloudydesk/files/systemd/cloudydesk.service /usr/lib/systemd/system/cloudydesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload cloudydesk.service: Unit cloudydesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/cloudydesk.service:10: Executable path is not absolute: pkill -f "cloudydesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/cloudydesk.service
		fi
		systemctl daemon-reload
		systemctl enable cloudydesk
		systemctl start cloudydesk
	fi
fi
