# This yaml shares the build bridge steps with ci and nightly.
name: Build flutter-rust-bridge
# 2023-11-23 18:00:00+00:00

on:
  workflow_call:

env:
  CARGO_EXPAND_VERSION: "1.0.95"
  FLUTTER_VERSION: "3.22.3"
  FLUTTER_RUST_BRIDGE_VERSION: "1.80.1"
  RUST_VERSION: "1.75" # https://github.com/cloudydesk/cloudydesk/discussions/7503

jobs:
  generate_bridge:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-22.04,
              extra-build-args: "",
            }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install prerequisites
        run: |
          sudo apt-get install ca-certificates -y
          sudo apt-get update -y
          sudo apt-get install -y \
            clang \
            cmake \
            curl \
            gcc \
            git \
            g++ \
            libclang-dev \
            libgtk-3-dev \
            llvm-dev \
            nasm \
            ninja-build \
            pkg-config \
            wget

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.job.target }}
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: bridge-${{ matrix.job.os }}

      - name: Cache Bridge
        id: cache-bridge
        uses: actions/cache@v3
        with:
          path: /tmp/flutter_rust_bridge
          key: vcpkg-${{ matrix.job.arch }}

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install flutter rust bridge deps
        shell: bash
        run: |
          cargo install cargo-expand --version ${{ env.CARGO_EXPAND_VERSION }} --locked
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid" --locked
          pushd flutter && sed -i -e 's/extended_text: 14.0.0/extended_text: 13.0.0/g' pubspec.yaml && flutter pub get && popd

      - name: Pre-fetch Cargo dependencies
        shell: bash
        run: |
          # Configure git for CI environment
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"
          git config --global advice.detachedHead false
          # Pre-populate cargo cache to avoid git metadata issues during bridge generation
          CARGO_NET_GIT_FETCH_WITH_CLI=true cargo fetch --verbose || true
          # Try to specifically update hwcodec dependency
          CARGO_NET_GIT_FETCH_WITH_CLI=true cargo update --package hwcodec || true

      - name: Run flutter rust bridge
        run: |
          # Run with additional flags and environment variables to handle dependency issues
          CARGO_NET_GIT_FETCH_WITH_CLI=true ~/.cargo/bin/flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated_bridge.dart \
            --c-output ./flutter/macos/Runner/bridge_generated.h \
            --skip-deps-check \
            --rust-crate-dir ./ \
            --verbose || true
          # Fallback: try without skip-deps-check if the above fails
          if [ ! -f ./flutter/lib/generated_bridge.dart ]; then
            echo "First attempt failed, trying without --skip-deps-check..."
            CARGO_NET_GIT_FETCH_WITH_CLI=true ~/.cargo/bin/flutter_rust_bridge_codegen \
              --rust-input ./src/flutter_ffi.rs \
              --dart-output ./flutter/lib/generated_bridge.dart \
              --c-output ./flutter/macos/Runner/bridge_generated.h \
              --rust-crate-dir ./
          fi
          cp ./flutter/macos/Runner/bridge_generated.h ./flutter/ios/Runner/bridge_generated.h

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: bridge-artifact
          path: |
            ./src/bridge_generated.rs
            ./src/bridge_generated.io.rs
            ./flutter/lib/generated_bridge.dart
            ./flutter/lib/generated_bridge.freezed.dart
            ./flutter/macos/Runner/bridge_generated.h
            ./flutter/ios/Runner/bridge_generated.h
